<<<<<<< HEAD
title: WTF is Ray Antony
timezone: America/Los_Angeles
gems: 		     [jekyll-paginate]
tagline: a G.H. Pages Blog
url: //rayantony.github.io
baseurl: ""
Description: Disclosures, reflections, and code tell the fragmented story of life
  post embezzlement
permalink: pretty
future: true
# relative_permalinks: true
=======
---
title: WTF is Ray Antony
timezone: America/Los_Angeles
collections:
  data:
    title: Data
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: a G.H. Pages Blog
url: https://rayantony.github.io
baseurl: "/"
Description: Disclosures, reflections, and code tell the fragmented story of life
  post embezzlement
permalink: pretty
>>>>>>> 2fb06fc538d1eb9e6189ae727b8324a7d5cf2b21
paginate: 5
author:
  name: Ray Anthony
  url: https://rayantony.github.io/
  email: ray@rayantony.com
<<<<<<< HEAD
  repo: https://github.com/rayrc/bootsplat/
=======
  repo: https://github.com/rayantony/
>>>>>>> 2fb06fc538d1eb9e6189ae727b8324a7d5cf2b21
  twitter: https://twitter.com/rayanthonyrcc/
  twitter_username: rayanthonyrcc
  github_username: rayantony
  aboutme_username: https://about.me/rayanthony
  lastfm_username: deadflowers
  pandora_username: ray517
  codepen_username: rayrc
  jsfiddle_username: rayrc
github:
  url: https://rayantony.github.io/
  repo: https://github.com/rayantony/rayantony.github.io
  user: https://github.com/rayantony/
  org: https://github.com/rayrc/
  team: https://github.com/rayrc/
markdown: kramdown
<<<<<<< HEAD
highlighter: pygments
kramdown:
  input: GFM
#  syntax_highlighter: rouge
=======
kramdown:
  input: GFM
  syntax_highlighter: rouge
>>>>>>> 2fb06fc538d1eb9e6189ae727b8324a7d5cf2b21
version: 1.0.0
