---
title: Ray Antony
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
relative_permalinks: true
tagline: A Git Blog
url: http://rayantony.github.io
paginate: 1
baseurl: "/"
author:
  name: Ray Antony
  url: https://twitter.com/rayanthonyrcc
  email: ray@rayantony.com
version: 1.0.0
github:
  repo: https://github.com/rayantony/rayantony.github.io
