---
title: Ray Antony
timezone: America/Los_Angeles
collections:
  business:
    title: Business
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
relative_permalinks: true
tagline: Ray Anthony GH Blog
url: http://rayantony.github.io
paginate: 4
baseurl: "/"
author:
  name: Ray Anthony
  url: https://twitter.com/rayanthonyrcc
  email: ray@rayantony.com
version: 1.0.0
github:
  repo: rayantony/rayantony.github.io
